[build]
  command = "cd web-app && yarn install && yarn add typescript@5.2.2 --dev && yarn build"
  publish = "web-app/dist"

[build.environment]
  NODE_VERSION = "22.14.0"
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--no-optional" 