services:
  - type: web
    name: wecook-api
    env: node
    buildCommand: |
      yarn install
      cd backend && yarn install && yarn build
    startCommand: cd backend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://wecook.onrender.com

  - type: web
    name: wecook
    env: node
    buildCommand: |
      yarn install
      cd web-app && yarn install && yarn build
    startCommand: cd web-app && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://wecook-api.onrender.com
