services:
  - type: web
    name: wecook-api
    env: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://wecook.onrender.com

  - type: web
    name: wecook
    env: node
    rootDir: web-app
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://wecook-api.onrender.com
